import { env } from '../../config/env';

const PERPLEXITY_API_URL = 'https://api.perplexity.ai/chat/completions';

export interface FoundMentor {
  name: string;
  title: string;
  company: string;
  bio: string;
  expertise: string[];
  // linkedinUrl is constructed from name+title+company — never generated by AI (hallucination risk)
  yearsExperience: number;
}

// Build a guaranteed-working LinkedIn people search URL from name + role context
export const buildLinkedInSearchUrl = (name: string, title: string, company: string): string => {
  const keywords = [name, title, company].filter(Boolean).join(' ');
  return `https://www.linkedin.com/search/results/people/?keywords=${encodeURIComponent(keywords)}`;
};

const SYSTEM_PROMPT = `You are a professional mentor researcher. Find REAL, specific professionals who work in a given field and would make great mentors for early-career people.

Key requirements:
- Identify professionals by NAME, JOB TITLE, and COMPANY — real people you can actually verify
- 3-8 years of experience (not entry level, not C-suite / famous — we want people who reply to messages)
- Must be genuinely active in the field, not just adjacent
- Write their bio based on what you know about their public professional background
- DO NOT include any LinkedIn URLs — those will be generated separately

Return ONLY valid JSON array, no markdown, no preamble.

Output format:
[
  {
    "name": "Full Name",
    "title": "Exact Job Title",
    "company": "Company or Organization Name",
    "bio": "2-3 sentences about their professional background, what they've worked on, and why they're a good mentor for someone entering this field",
    "expertise": ["skill1", "skill2", "skill3"],
    "yearsExperience": 5
  }
]`;

export const searchMentorsWithAI = async (input: {
  primaryPath: string;
  pathTitles?: string[];
  skills: string[];
  values: string[];
}): Promise<FoundMentor[]> => {
  if (!env.PERPLEXITY_API_KEY) return [];

  const roleLines = (input.pathTitles ?? [input.primaryPath])
    .filter(Boolean)
    .map((t) => `  - ${t}`)
    .join('\n');

  const userPrompt = `Find 5 real professionals who are excellent mentors for someone targeting these career paths:

Target Roles:
${roleLines}

Mentee context:
- Skills: ${input.skills.slice(0, 8).join(', ') || 'not specified'}
- Values: ${input.values.join(', ') || 'growth, impact'}

For each mentor:
- They must work in one of the target roles above — highly specific match
- 3-8 years experience (approachable, not yet at the top of their field)
- Mix: some at large companies, some at startups, some independent/freelance
- Prefer UK-based or open to global connections
- Write a bio that highlights specifically why they're relevant to this mentee's path`;

  try {
    const response = await fetch(PERPLEXITY_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${env.PERPLEXITY_API_KEY}`,
        ...(env.PERPLEXITY_GROUP_ID ? { 'X-Group-Id': env.PERPLEXITY_GROUP_ID } : {}),
      },
      body: JSON.stringify({
        model: 'sonar-pro',
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userPrompt },
        ],
        temperature: 0.3,
        max_tokens: 2500,
      }),
    });

    if (!response.ok) {
      console.error('[MentorSearch] Perplexity error:', await response.text());
      return [];
    }

    const data = await response.json() as { choices: Array<{ message: { content: string } }> };
    const content = data.choices?.[0]?.message?.content ?? '';
    const cleaned = content.replace(/^```json\n?/, '').replace(/\n?```$/, '').trim();

    const parsed = JSON.parse(cleaned) as FoundMentor[];

    return parsed
      .filter((m) => m.name && m.title && m.company)
      .map((m) => ({
        name: m.name,
        title: m.title,
        company: m.company,
        bio: m.bio ?? '',
        expertise: Array.isArray(m.expertise) ? m.expertise.slice(0, 5) : [],
        yearsExperience: m.yearsExperience ?? 3,
      }));
  } catch (err) {
    console.error('[MentorSearch] Failed to parse response:', err);
    return [];
  }
};
